[package]
name = "receiver"
version = "0.1.0"
authors = [""]
edition = "2021"

[dependencies]
rust-chain = { version="0.2", default-features = false }

[lib]
name = "receiver"
path = "lib.rs"
crate-type = ["cdylib", "rlib"]

[features]
default = ["std"]
std = [
    "rust-chain/std",
]

